// Copyright (c) 2005-2011 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
//

#ifndef DATA_PSKEL_HPP
#define DATA_PSKEL_HPP

#include <xsde/cxx/version.hxx>

#if (XSDE_INT_VERSION != 3020000L)
#error XSD/e runtime version mismatch
#endif

#include <xsde/cxx/config.hxx>

#ifndef XSDE_ENCODING_UTF8
#error the generated code uses the UTF-8 encodingwhile the XSD/e runtime does not (reconfigure the runtime or change the --char-encoding value)
#endif

#ifndef XSDE_STL
#error the generated code uses STL while the XSD/e runtime does not (reconfigure the runtime or add --no-stl)
#endif

#ifndef XSDE_IOSTREAM
#error the generated code uses iostream while the XSD/e runtime does not (reconfigure the runtime or add --no-iostream)
#endif

#ifndef XSDE_EXCEPTIONS
#error the generated code uses exceptions while the XSD/e runtime does not (reconfigure the runtime or add --no-exceptions)
#endif

#ifndef XSDE_LONGLONG
#error the generated code uses long long while the XSD/e runtime does not (reconfigure the runtime or add --no-long-long)
#endif

#ifdef XSDE_PARSER_VALIDATION
#error the XSD/e runtime uses validation while the generated code does not (reconfigure the runtime or remove --suppress-validation)
#endif

#ifdef XSDE_POLYMORPHIC
#error the generated code expects XSD/e runtime without polymorphism support (reconfigure the runtime or add --generate-polymorphic/--runtime-polymorphic)
#endif

#ifndef XSDE_REUSE_STYLE_TIEIN
#error the generated code uses the tiein reuse style while the XSD/e runtime does not (reconfigure the runtime or add --reuse-style-mixin or --reuse-style-none)
#endif

#ifdef XSDE_CUSTOM_ALLOCATOR
#error the XSD/e runtime uses custom allocator while the generated code does not (reconfigure the runtime or add --custom-allocator)
#endif

#include <xsde/cxx/pre.hxx>

// Begin prologue.
//

#include <xsde/cxx/hybrid/any-type.hxx>
#include <xsde/cxx/hybrid/any-type-pskel.hxx>
#include <xsde/cxx/hybrid/any-type-pimpl.hxx>

namespace xml_schema
{
  using ::xsde::cxx::hybrid::any_type;

  using ::xsde::cxx::hybrid::any_type_pskel;
  using ::xsde::cxx::hybrid::any_type_pimpl;
}


//
// End prologue.

// Forward declarations
//
namespace N_Data
{
  class RootDir_pskel;
  class DataPath_pskel;
  class Data_pskel;
}


#include <xsde/cxx/ro-string.hxx>

#include <xsde/cxx/parser/xml-schema.hxx>

#include <xsde/cxx/parser/exceptions.hxx>

#include <xsde/cxx/parser/non-validating/parser.hxx>
#include <xsde/cxx/parser/non-validating/xml-schema-pskel.hxx>
#include <xsde/cxx/parser/non-validating/xml-schema-pimpl.hxx>

#include <xsde/cxx/parser/expat/document.hxx>

#include "Data.hpp"

namespace xml_schema
{
  // Built-in XML Schema types mapping.
  //
  using ::xsde::cxx::string_sequence;
  using ::xsde::cxx::qname;
  using ::xsde::cxx::buffer;
  using ::xsde::cxx::time_zone;
  using ::xsde::cxx::gday;
  using ::xsde::cxx::gmonth;
  using ::xsde::cxx::gyear;
  using ::xsde::cxx::gmonth_day;
  using ::xsde::cxx::gyear_month;
  using ::xsde::cxx::date;
  using ::xsde::cxx::time;
  using ::xsde::cxx::date_time;
  using ::xsde::cxx::duration;

  // Base parser skeletons.
  //
  using ::xsde::cxx::parser::parser_base;
  typedef ::xsde::cxx::parser::non_validating::empty_content parser_empty_content;
  typedef ::xsde::cxx::parser::non_validating::simple_content parser_simple_content;
  typedef ::xsde::cxx::parser::non_validating::complex_content parser_complex_content;
  typedef ::xsde::cxx::parser::non_validating::list_base parser_list_base;

  // Parser skeletons and implementations for the XML Schema
  // built-in types.
  //
  using ::xsde::cxx::parser::non_validating::any_simple_type_pskel;
  using ::xsde::cxx::parser::non_validating::any_simple_type_pimpl;

  using ::xsde::cxx::parser::non_validating::byte_pskel;
  using ::xsde::cxx::parser::non_validating::byte_pimpl;

  using ::xsde::cxx::parser::non_validating::unsigned_byte_pskel;
  using ::xsde::cxx::parser::non_validating::unsigned_byte_pimpl;

  using ::xsde::cxx::parser::non_validating::short_pskel;
  using ::xsde::cxx::parser::non_validating::short_pimpl;

  using ::xsde::cxx::parser::non_validating::unsigned_short_pskel;
  using ::xsde::cxx::parser::non_validating::unsigned_short_pimpl;

  using ::xsde::cxx::parser::non_validating::int_pskel;
  using ::xsde::cxx::parser::non_validating::int_pimpl;

  using ::xsde::cxx::parser::non_validating::unsigned_int_pskel;
  using ::xsde::cxx::parser::non_validating::unsigned_int_pimpl;

  using ::xsde::cxx::parser::non_validating::long_pskel;
  using ::xsde::cxx::parser::non_validating::long_pimpl;

  using ::xsde::cxx::parser::non_validating::unsigned_long_pskel;
  using ::xsde::cxx::parser::non_validating::unsigned_long_pimpl;

  using ::xsde::cxx::parser::non_validating::integer_pskel;
  using ::xsde::cxx::parser::non_validating::integer_pimpl;

  using ::xsde::cxx::parser::non_validating::non_positive_integer_pskel;
  using ::xsde::cxx::parser::non_validating::non_positive_integer_pimpl;

  using ::xsde::cxx::parser::non_validating::non_negative_integer_pskel;
  using ::xsde::cxx::parser::non_validating::non_negative_integer_pimpl;

  using ::xsde::cxx::parser::non_validating::positive_integer_pskel;
  using ::xsde::cxx::parser::non_validating::positive_integer_pimpl;

  using ::xsde::cxx::parser::non_validating::negative_integer_pskel;
  using ::xsde::cxx::parser::non_validating::negative_integer_pimpl;

  using ::xsde::cxx::parser::non_validating::boolean_pskel;
  using ::xsde::cxx::parser::non_validating::boolean_pimpl;

  using ::xsde::cxx::parser::non_validating::float_pskel;
  using ::xsde::cxx::parser::non_validating::float_pimpl;

  using ::xsde::cxx::parser::non_validating::double_pskel;
  using ::xsde::cxx::parser::non_validating::double_pimpl;

  using ::xsde::cxx::parser::non_validating::decimal_pskel;
  using ::xsde::cxx::parser::non_validating::decimal_pimpl;

  using ::xsde::cxx::parser::non_validating::string_pskel;
  using ::xsde::cxx::parser::non_validating::string_pimpl;

  using ::xsde::cxx::parser::non_validating::normalized_string_pskel;
  using ::xsde::cxx::parser::non_validating::normalized_string_pimpl;

  using ::xsde::cxx::parser::non_validating::token_pskel;
  using ::xsde::cxx::parser::non_validating::token_pimpl;

  using ::xsde::cxx::parser::non_validating::name_pskel;
  using ::xsde::cxx::parser::non_validating::name_pimpl;

  using ::xsde::cxx::parser::non_validating::nmtoken_pskel;
  using ::xsde::cxx::parser::non_validating::nmtoken_pimpl;

  using ::xsde::cxx::parser::non_validating::nmtokens_pskel;
  using ::xsde::cxx::parser::non_validating::nmtokens_pimpl;

  using ::xsde::cxx::parser::non_validating::ncname_pskel;
  using ::xsde::cxx::parser::non_validating::ncname_pimpl;

  using ::xsde::cxx::parser::non_validating::language_pskel;
  using ::xsde::cxx::parser::non_validating::language_pimpl;

  using ::xsde::cxx::parser::non_validating::id_pskel;
  using ::xsde::cxx::parser::non_validating::id_pimpl;

  using ::xsde::cxx::parser::non_validating::idref_pskel;
  using ::xsde::cxx::parser::non_validating::idref_pimpl;

  using ::xsde::cxx::parser::non_validating::idrefs_pskel;
  using ::xsde::cxx::parser::non_validating::idrefs_pimpl;

  using ::xsde::cxx::parser::non_validating::uri_pskel;
  using ::xsde::cxx::parser::non_validating::uri_pimpl;

  using ::xsde::cxx::parser::non_validating::qname_pskel;
  using ::xsde::cxx::parser::non_validating::qname_pimpl;

  using ::xsde::cxx::parser::non_validating::base64_binary_pskel;
  using ::xsde::cxx::parser::non_validating::base64_binary_pimpl;

  using ::xsde::cxx::parser::non_validating::hex_binary_pskel;
  using ::xsde::cxx::parser::non_validating::hex_binary_pimpl;

  using ::xsde::cxx::parser::non_validating::date_pskel;
  using ::xsde::cxx::parser::non_validating::date_pimpl;

  using ::xsde::cxx::parser::non_validating::date_time_pskel;
  using ::xsde::cxx::parser::non_validating::date_time_pimpl;

  using ::xsde::cxx::parser::non_validating::duration_pskel;
  using ::xsde::cxx::parser::non_validating::duration_pimpl;

  using ::xsde::cxx::parser::non_validating::gday_pskel;
  using ::xsde::cxx::parser::non_validating::gday_pimpl;

  using ::xsde::cxx::parser::non_validating::gmonth_pskel;
  using ::xsde::cxx::parser::non_validating::gmonth_pimpl;

  using ::xsde::cxx::parser::non_validating::gmonth_day_pskel;
  using ::xsde::cxx::parser::non_validating::gmonth_day_pimpl;

  using ::xsde::cxx::parser::non_validating::gyear_pskel;
  using ::xsde::cxx::parser::non_validating::gyear_pimpl;

  using ::xsde::cxx::parser::non_validating::gyear_month_pskel;
  using ::xsde::cxx::parser::non_validating::gyear_month_pimpl;

  using ::xsde::cxx::parser::non_validating::time_pskel;
  using ::xsde::cxx::parser::non_validating::time_pimpl;

  // Read-only string.
  //
  using ::xsde::cxx::ro_string;

  // Error codes.
  //
  typedef xsde::cxx::parser::expat::xml_error parser_xml_error;

  // Exceptions.
  //
  typedef xsde::cxx::parser::exception parser_exception;
  typedef xsde::cxx::parser::xml parser_xml;

  // Document parser.
  //
  using xsde::cxx::parser::expat::document_pimpl;

  // Parser context.
  //
  typedef xsde::cxx::parser::context parser_context;
}

namespace N_Data
{
  class RootDir_pskel: public ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual ::N_Data::RootDir
    post_RootDir () = 0;

    // Constructor.
    //
    RootDir_pskel (::xml_schema::string_pskel* tiein);

    // Implementation details.
    //
    virtual ::std::string
    post_string ();

    protected:
    RootDir_pskel* RootDir_impl_;
    RootDir_pskel (RootDir_pskel*, void*);
  };

  class DataPath_pskel: public ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    // Attributes.
    //
    virtual void
    name (const ::std::string&);

    virtual ::N_Data::DataPath
    post_DataPath () = 0;

    // Parser construction API.
    //
    void
    parsers (::xml_schema::string_pskel& /* name */);

    // Individual attribute parsers.
    //
    void
    name_parser (::xml_schema::string_pskel&);

    virtual void
    _reset ();

    // Constructor.
    //
    DataPath_pskel (::xml_schema::string_pskel* tiein);

    // Implementation details.
    //
    virtual ::std::string
    post_string ();

    protected:
    DataPath_pskel* DataPath_impl_;
    DataPath_pskel (DataPath_pskel*, void*);

    protected:
    virtual bool
    _attribute_impl (const ::xsde::cxx::ro_string&,
                     const ::xsde::cxx::ro_string&,
                     const ::xsde::cxx::ro_string&);

    protected:
    ::xml_schema::string_pskel* name_parser_;
  };

  class Data_pskel: public ::xsde::cxx::parser::non_validating::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    // Elements.
    //
    virtual void
    RootDir (const ::N_Data::RootDir&);

    virtual void
    DataPath (const ::N_Data::DataPath&);

    virtual ::N_Data::Data*
    post_Data () = 0;

    // Parser construction API.
    //
    void
    parsers (::N_Data::RootDir_pskel& /* RootDir */,
             ::N_Data::DataPath_pskel& /* DataPath */);

    // Individual element parsers.
    //
    void
    RootDir_parser (::N_Data::RootDir_pskel&);

    void
    DataPath_parser (::N_Data::DataPath_pskel&);

    virtual void
    _reset ();

    // Constructor.
    //
    Data_pskel ();

    // Implementation details.
    //
    protected:
    Data_pskel* Data_impl_;
    Data_pskel (Data_pskel*, void*);

    protected:
    virtual bool
    _start_element_impl (const ::xsde::cxx::ro_string&,
                         const ::xsde::cxx::ro_string&);

    virtual bool
    _end_element_impl (const ::xsde::cxx::ro_string&,
                       const ::xsde::cxx::ro_string&);

    protected:
    ::N_Data::RootDir_pskel* RootDir_parser_;
    ::N_Data::DataPath_pskel* DataPath_parser_;
  };
}

// Begin epilogue.
//
//
// End epilogue.

#include <xsde/cxx/post.hxx>

#endif // DATA_PSKEL_HPP
